import { upsertByUID } from '../utils/seed-helpers';

type InsightSeed = {
  slug: string;
  titleKey: string;
  descriptionKey: string;
  scope: 'interprovincial' | 'international' | 'all';
  intrant: 'energy' | 'agriculture' | 'manufacturing' | 'services' | 'all';
  kind: 'summary' | 'insight';
  value?: number;
  change?: number;
  unitKey?: string;
  period?: string;
  province?: string;
  country?: 'CA' | 'DE' | 'FR' | 'IT' | 'JP' | 'UK' | 'US';
  ordinal?: number;
};

const insights: InsightSeed[] = [
  {
    slug: 'energy-flow',
    titleKey: 'pages.statistics.summaries.energyFlow.title',
    descriptionKey: 'pages.statistics.summaries.energyFlow.description',
    scope: 'interprovincial',
    intrant: 'energy',
    kind: 'summary',
    value: 620,
    change: 8,
    unitKey: 'pages.statistics.units.petajoules',
    period: '2024-Q2',
    province: 'CA-AB',
    country: 'CA',
    ordinal: 1,
  },
  {
    slug: 'clean-tech-demand',
    titleKey: 'pages.statistics.summaries.cleanTechDemand.title',
    descriptionKey: 'pages.statistics.summaries.cleanTechDemand.description',
    scope: 'interprovincial',
    intrant: 'manufacturing',
    kind: 'summary',
    value: 92,
    change: 5,
    unitKey: 'pages.statistics.units.projects',
    period: '2024-Q2',
    province: 'CA-QC',
    country: 'CA',
    ordinal: 2,
  },
  {
    slug: 'agri-value',
    titleKey: 'pages.statistics.summaries.agriValue.title',
    descriptionKey: 'pages.statistics.summaries.agriValue.description',
    scope: 'interprovincial',
    intrant: 'agriculture',
    kind: 'summary',
    value: 41,
    change: 3,
    unitKey: 'pages.statistics.units.billionCAD',
    period: '2024-Q2',
    province: 'CA-SK',
    country: 'CA',
    ordinal: 3,
  },
  {
    slug: 'energy-flow-global',
    titleKey: 'pages.statistics.summaries.energyFlowGlobal.title',
    descriptionKey: 'pages.statistics.summaries.energyFlowGlobal.description',
    scope: 'international',
    intrant: 'energy',
    kind: 'summary',
    value: 510,
    change: 6,
    unitKey: 'pages.statistics.units.petajoules',
    period: '2024-Q1',
    province: 'CA-NL',
    country: 'CA',
    ordinal: 4,
  },
  {
    slug: 'services-exports',
    titleKey: 'pages.statistics.summaries.servicesExports.title',
    descriptionKey: 'pages.statistics.summaries.servicesExports.description',
    scope: 'international',
    intrant: 'services',
    kind: 'summary',
    value: 128,
    change: 4,
    unitKey: 'pages.statistics.units.billionCAD',
    period: '2024-Q1',
    province: 'CA-ON',
    country: 'CA',
    ordinal: 5,
  },
  {
    slug: 'agri-global-share',
    titleKey: 'pages.statistics.summaries.agriGlobalShare.title',
    descriptionKey: 'pages.statistics.summaries.agriGlobalShare.description',
    scope: 'international',
    intrant: 'agriculture',
    kind: 'summary',
    value: 27,
    change: -2,
    unitKey: 'pages.statistics.units.marketShare',
    period: '2024-Q1',
    province: 'CA-MB',
    country: 'CA',
    ordinal: 6,
  },
  {
    slug: 'digital-services',
    titleKey: 'pages.statistics.summaries.digitalServices.title',
    descriptionKey: 'pages.statistics.summaries.digitalServices.description',
    scope: 'interprovincial',
    intrant: 'services',
    kind: 'summary',
    value: 74,
    change: 11,
    unitKey: 'pages.statistics.units.billionCAD',
    period: '2024-Q3',
    province: 'CA-BC',
    country: 'CA',
    ordinal: 7,
  },
  {
    slug: 'manufacturing-alliances',
    titleKey: 'pages.statistics.summaries.manufacturingAlliances.title',
    descriptionKey: 'pages.statistics.summaries.manufacturingAlliances.description',
    scope: 'international',
    intrant: 'manufacturing',
    kind: 'summary',
    value: 36,
    change: 9,
    unitKey: 'pages.statistics.units.alliances',
    period: '2024-Q3',
    province: 'CA-ON',
    country: 'CA',
    ordinal: 8,
  },
  {
    slug: 'agri-resilience',
    titleKey: 'pages.statistics.summaries.agriResilience.title',
    descriptionKey: 'pages.statistics.summaries.agriResilience.description',
    scope: 'interprovincial',
    intrant: 'agriculture',
    kind: 'summary',
    value: 18,
    change: 7,
    unitKey: 'pages.statistics.units.cooperatives',
    period: '2024-Q3',
    province: 'CA-QC',
    country: 'CA',
    ordinal: 9,
  },
  {
    slug: 'g7-us-investment',
    titleKey: 'pages.statistics.countries.us.title',
    descriptionKey: 'pages.statistics.countries.us.description',
    scope: 'international',
    intrant: 'all',
    kind: 'summary',
    value: 540,
    change: 6,
    unitKey: 'pages.statistics.units.billionCAD',
    period: '2024-Q2',
    country: 'US',
    ordinal: 20,
  },
  {
    slug: 'g7-uk-clean-energy',
    titleKey: 'pages.statistics.countries.uk.title',
    descriptionKey: 'pages.statistics.countries.uk.description',
    scope: 'international',
    intrant: 'energy',
    kind: 'summary',
    value: 215,
    change: 4,
    unitKey: 'pages.statistics.units.billionCAD',
    period: '2024-Q2',
    country: 'UK',
    ordinal: 21,
  },
  {
    slug: 'g7-fr-innovation',
    titleKey: 'pages.statistics.countries.fr.title',
    descriptionKey: 'pages.statistics.countries.fr.description',
    scope: 'international',
    intrant: 'manufacturing',
    kind: 'summary',
    value: 198,
    change: 5,
    unitKey: 'pages.statistics.units.billionCAD',
    period: '2024-Q1',
    country: 'FR',
    ordinal: 22,
  },
  {
    slug: 'g7-de-hydrogen',
    titleKey: 'pages.statistics.countries.de.title',
    descriptionKey: 'pages.statistics.countries.de.description',
    scope: 'international',
    intrant: 'energy',
    kind: 'summary',
    value: 260,
    change: 7,
    unitKey: 'pages.statistics.units.billionCAD',
    period: '2024-Q1',
    country: 'DE',
    ordinal: 23,
  },
  {
    slug: 'g7-it-circular',
    titleKey: 'pages.statistics.countries.it.title',
    descriptionKey: 'pages.statistics.countries.it.description',
    scope: 'international',
    intrant: 'services',
    kind: 'summary',
    value: 142,
    change: 3,
    unitKey: 'pages.statistics.units.billionCAD',
    period: '2024-Q2',
    country: 'IT',
    ordinal: 24,
  },
  {
    slug: 'g7-jp-advanced',
    titleKey: 'pages.statistics.countries.jp.title',
    descriptionKey: 'pages.statistics.countries.jp.description',
    scope: 'international',
    intrant: 'manufacturing',
    kind: 'summary',
    value: 310,
    change: 8,
    unitKey: 'pages.statistics.units.billionCAD',
    period: '2024-Q2',
    country: 'JP',
    ordinal: 25,
  },
  {
    slug: 'partnership-low-carbon',
    titleKey: 'pages.statistics.sections.partnerships.cards.lowCarbon.title',
    descriptionKey: 'pages.statistics.sections.partnerships.cards.lowCarbon.body',
    scope: 'all',
    intrant: 'energy',
    kind: 'insight',
    ordinal: 1,
  },
  {
    slug: 'partnership-innovation',
    titleKey: 'pages.statistics.sections.partnerships.cards.innovation.title',
    descriptionKey: 'pages.statistics.sections.partnerships.cards.innovation.body',
    scope: 'all',
    intrant: 'manufacturing',
    kind: 'insight',
    ordinal: 2,
  },
  {
    slug: 'partnership-skills',
    titleKey: 'pages.statistics.sections.partnerships.cards.skills.title',
    descriptionKey: 'pages.statistics.sections.partnerships.cards.skills.body',
    scope: 'all',
    intrant: 'services',
    kind: 'insight',
    ordinal: 3,
  },
  {
    slug: 'partnership-infrastructure',
    titleKey: 'pages.statistics.sections.partnerships.cards.infrastructure.title',
    descriptionKey: 'pages.statistics.sections.partnerships.cards.infrastructure.body',
    scope: 'all',
    intrant: 'manufacturing',
    kind: 'insight',
    ordinal: 4,
  },
  {
    slug: 'partnership-sme',
    titleKey: 'pages.statistics.sections.partnerships.cards.sme.title',
    descriptionKey: 'pages.statistics.sections.partnerships.cards.sme.body',
    scope: 'all',
    intrant: 'services',
    kind: 'insight',
    ordinal: 5,
  },
  {
    slug: 'partnership-digital',
    titleKey: 'pages.statistics.sections.partnerships.cards.digital.title',
    descriptionKey: 'pages.statistics.sections.partnerships.cards.digital.body',
    scope: 'all',
    intrant: 'services',
    kind: 'insight',
    ordinal: 6,
  },
];

export default async () => {
  for (const insight of insights) {
    // eslint-disable-next-line no-await-in-loop
    await upsertByUID('api::statistic-insight.statistic-insight', insight, {
      unique: { slug: insight.slug },
    });
  }
};
