/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sectors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provinces */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List companies */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exchanges */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/homepage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get homepage */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch statistics summaries */
        get: {
            parameters: {
                query?: {
                    scope?: "interprovincial" | "international" | "all";
                    intrant?: "all" | "energy" | "agriculture" | "manufacturing" | "services";
                    period?: string;
                    province?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatisticsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List billing plans */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["BillingPlan"][];
                            meta?: {
                                count: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Province: {
            id: number;
            name: string;
        };
        Sector: {
            id: number;
            name: string;
        };
        CompanyCapacity: {
            label: string;
            value?: number | null;
            unit?: string | null;
        };
        Company: {
            id: number;
            name: string;
            description?: string | null;
            website?: string | null;
            /** @enum {string} */
            status: "pending" | "approved" | "suspended";
            logoUrl?: string | null;
            secondaryLogoUrl?: string | null;
            capacities?: components["schemas"]["CompanyCapacity"][];
            sector?: components["schemas"]["Sector"];
            province?: components["schemas"]["Province"];
        };
        Exchange: {
            slug: string;
            title: {
                [key: string]: string;
            };
            value: number;
            unit: string;
            sourceProvince: number;
            targetProvince: number;
        };
        BillingPlanPrice: {
            amount: number;
            currency: string;
            /** @enum {string} */
            interval: "month" | "year";
        };
        BillingPlanCapabilities: {
            premiumVisibility: boolean;
            priorityAnalytics: boolean;
        };
        BillingPlan: {
            id: string;
            /** @enum {string} */
            tier: "free" | "premium";
            /** @enum {string} */
            provider: "internal" | "stripe";
            price: components["schemas"]["BillingPlanPrice"];
            features: string[];
            capabilities: components["schemas"]["BillingPlanCapabilities"];
            i18nKey: string;
            highlight: boolean;
            available: boolean;
        };
        StatisticsSummary: {
            id: number;
            slug?: string | null;
            /** @enum {string} */
            scope: "interprovincial" | "international" | "all";
            /** @enum {string} */
            intrant: "all" | "energy" | "agriculture" | "manufacturing" | "services";
            value?: number | null;
            change?: number | null;
            unitKey?: string | null;
            titleKey: string;
            descriptionKey: string;
            period?: string | null;
            province?: string | null;
        };
        StatisticsInsight: {
            id: number;
            slug?: string | null;
            /** @enum {string} */
            scope: "interprovincial" | "international" | "all";
            /** @enum {string} */
            intrant: "all" | "energy" | "agriculture" | "manufacturing" | "services";
            titleKey: string;
            descriptionKey: string;
            period?: string | null;
            province?: string | null;
        };
        StatisticsSnapshot: {
            totalFlows?: number | null;
            totalFlowsUnitKey?: string | null;
            activeCorridors: number;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        StatisticsResponse: {
            data: {
                summaries: components["schemas"]["StatisticsSummary"][];
                insights: components["schemas"]["StatisticsInsight"][];
                snapshot?: components["schemas"]["StatisticsSnapshot"];
                availablePeriods: string[];
                availableProvinces: string[];
            };
            meta?: {
                filters?: {
                    scope?: string | null;
                    intrant?: string | null;
                    period?: string | null;
                    province?: string | null;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
