AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution pour servir les assets statiques OpenG7 et fallback SSR

Parameters:
  DomainName:
    Type: String
    Description: "Domaine principal (ex: www.openg7.org)"
  CertificateArn:
    Type: String
    Description: "ARN du certificat ACM dans us-east-1"
  SsrOriginDomain:
    Type: String
    Description: "DNS public de l'Ingress SSR (ex: ssr.openg7.org)"
  PriceClass:
    Type: String
    Default: PriceClass_100
    AllowedValues:
      - PriceClass_100
      - PriceClass_200
      - PriceClass_All
    Description: "Couverture CloudFront"

Resources:
  StaticAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-static-assets"
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  StaticAssetsOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${DomainName}-oac"
        Description: OAC pour la distribution statique OpenG7
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  StaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssetsBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - !GetAtt StaticAssetsBucket.Arn
                - '/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${FrontendDistribution}"

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: OpenG7 CDN avec fallback SSR
        Aliases:
          - !Ref DomainName
        DefaultRootObject: index.html
        PriceClass: !Ref PriceClass
        Origins:
          - Id: StaticAssets
            DomainName: !GetAtt StaticAssetsBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref StaticAssetsOAC
          - Id: SsrBackend
            DomainName: !Ref SsrOriginDomain
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPSPort: 443
              OriginKeepaliveTimeout: 30
              OriginReadTimeout: 30
        OriginGroups:
          Quantity: 0
        DefaultCacheBehavior:
          TargetOriginId: SsrBackend
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
            Headers:
              - Accept-Language
              - Authorization
              - CloudFront-Forwarded-Proto
          MinTTL: 0
          DefaultTTL: 0
          MaxTTL: 0
        CacheBehaviors:
          - PathPattern: '*.js'
            TargetOriginId: StaticAssets
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
            ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03 # Managed-SecurityHeadersPolicy
          - PathPattern: '*.css'
            TargetOriginId: StaticAssets
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03
          - PathPattern: '/assets/*'
            TargetOriginId: StaticAssets
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Logging:
          IncludeCookies: false
          Bucket: !Sub '${StaticAssetsBucket}.s3.amazonaws.com'
          Prefix: cloudfront-logs/
        HttpVersion: http2
        IPV6Enabled: true

Outputs:
  DistributionId:
    Value: !Ref FrontendDistribution
    Description: ID de la distribution CloudFront
  StaticAssetsBucketName:
    Value: !Ref StaticAssetsBucket
    Description: Bucket contenant les assets buildés
